In [1]:
import numpy as np

## Problem 1

In [2]:
A = np.array([[3,-1,4],[1,5,-9]])
B = np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])

In [3]:
(np.dot(A, B))

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Problem 2

In [4]:
A = np.array([[3,1,4],[1, 5, 9],[-5, 3, 1]])
print(A)

[[ 3  1  4]
 [ 1  5  9]
 [-5  3  1]]


In [5]:
-(A@A@A)+9*(A@A)-15*A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Problem 3

In [6]:
A=np.ones((7,7), dtype=np.int)
A=np.triu(A)
print(A)

[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]


In [7]:
a=np.full_like(A,5)
b=np.full_like(A,-1)
a=np.triu(a)
b=np.tril(b)
a=a-np.eye(7,dtype=np.int)*5
B=a+b

In [8]:
print(B)

[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]


In [9]:
C= A@B@A
C=C.astype(np.int64)
print(C)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


## Problem 4

In [10]:
a=np.array([-3,-2,-1,0,1,2,3])

In [11]:
#as a function
def non_zero(a0):
    b=np.copy(a0)
    mask = b<0
    b[mask]=0
    return b

print(non_zero(a))

[0 0 0 0 1 2 3]


## Problem 5

In [12]:
A=np.array([[0,2,4],[1,3,5]])
B=np.array([[3,0,0],[3,3,0],[3,3,3]])
C=np.diag([-2,-2,-2])

In [13]:
Zero = np.column_stack((np.zeros((3,4)), A.T, np.eye(3)))
One = np.column_stack((A, np.zeros_like(A), np.zeros_like(A)))
Two= np.column_stack((B, np.zeros_like(B), C))

In [14]:
np.vstack((Zero, One,Two))

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0.,  0., -2.]])

## Problem 6

In [15]:
def myfun(A0):
    sums = A0.sum(axis=1)
    B = A0 / sums.reshape((len(sums),1))
    return B    

In [16]:
A = np.arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
print(myfun(A))

[[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]]


## Problem 7

In [18]:
import os
os.chdir('C:/Users/schue/Documents/OSELab 2019/BootCamp2019/Computation/Wk1_PyIntro')
grid = np.load("grid.npy")

In [19]:
np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])

48477312

In [20]:
np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])

51267216

In [21]:
np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])

40304286