# Intro to NumPy

## Arrays

In [2]:
# rebuild the code in the PDF
import numpy as np

# Create a 1-D array by passing a list into NumPy's array() function.
np.array([8,4,6,0,2])

[1 3 5 7 9]


In [ ]:
# The string representation has no commas or an array() label.
print(np.array([1, 3, 5, 7, 9]))

In [4]:
# Create a 2-D array by passing a list of lists into array().
A = np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [5]:
# Access elements of the array with brackets.
print(A[0,1],A[1,2])

2 6


In [6]:
# The elements of a 2-D array are 1-D arrays.
A[0]

array([1, 2, 3])

### Problem 1

In [9]:
A = np.array([[3,-1,4],[1,5,-9]])
B = np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]])

#check:
print(B)

[[ 2  6 -5  3]
 [ 5 -8  9  7]
 [ 9 -3 -2 -3]]


In [12]:
(np.dot(A, B))

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

## Basic Array Operations

In [13]:
# Addition concatenates lists together.
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [14]:
# Mutliplication concatenates a list with itself a given number of times.
[1,2,3]*4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [17]:
x,y = np.array([1,2,3]), np.array([4,5,6])
x+10

array([11, 12, 13])

In [18]:
x*4

array([ 4,  8, 12])

In [19]:
x+y

array([5, 7, 9])

In [20]:
x*y

array([ 4, 10, 18])

### Problem 2

In [25]:
A = np.array([[3,1,4],[1, 5, 9],[-5, 3, 1]])
print(A)

[[ 3  1  4]
 [ 1  5  9]
 [-5  3  1]]


In [26]:
-(A@A@A)+9*(A@A)-15*A

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Array Attributes

In [28]:
A = np.array([[1, 2, 3],[4, 5, 6]])
print (A)

[[1 2 3]
 [4 5 6]]


In [29]:
print(A.ndim, A.shape, A.size)

2 (2, 3) 6


## Array Creation Routines

In [30]:
# A 1-D array of 5 zeros.
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
# A 2x5 matrix (2-D array) of integer ones.
np.ones((2,5), dtype=np.int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
I= np.eye(2)
print(I)

[[1. 0.]
 [0. 1.]]


In [33]:
np.full_like(I,3)

array([[3., 3.],
       [3., 3.]])

In [34]:
# A list of integers becomes an array of integers.
x=np.array([0,1,2,3,4])
print(x)

[0 1 2 3 4]


In [35]:
x.dtype

dtype('int32')

In [37]:
# Change the data type to one of NumPy's float types.
x=x.astype(np.float64)
print(x)

[0. 1. 2. 3. 4.]


In [38]:
x.dtype

dtype('float64')

In [45]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
# Get only the upper triangular entries of 'A'.
np.triu(A)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [41]:
# Get the diagonal entries of 'A' as a 1-D array.
np.diag(A)

array([1, 5, 9])

In [42]:
# diag() can also be used to create a diagonal matrix from a 1-D array.
np.diag([1,11,111])

array([[  1,   0,   0],
       [  0,  11,   0],
       [  0,   0, 111]])

### Problem 3

In [52]:
A=np.ones((7,7), dtype=np.int)
A=np.triu(A)
print(A)

[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]


In [84]:
a=np.full_like(A,5)
b=np.full_like(A,-1)
a=np.triu(a)
b=np.tril(b)
a=a-np.eye(7,dtype=np.int)*5
B=a+b

In [85]:
print(B)

[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]


In [88]:
C= A@B@A
C=C.astype(np.int64)
print(C)

[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


## Data Access

## Array Slicing

In [92]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
x[3],x[3:], x[:3], x[3:8]

(3, array([3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2]), array([3, 4, 5, 6, 7]))

In [98]:
A = np.array([[0,1,2,3,4],[5,6,7,8,9]])
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [100]:
A[1,2], A[:, 2:]

(7, array([[2, 3, 4],
        [7, 8, 9]]))

## Fancy Indexing

In [101]:
x=np.arange(0,50,10)
x

array([ 0, 10, 20, 30, 40])

In [102]:
index=np.array([3,1,4])
x[index]

array([30, 10, 40])

In [103]:
mask=np.array([True, False, False, True, False])
x[mask]

array([ 0, 30])

In [104]:
y=np.arange(10,20,2)
y

array([10, 12, 14, 16, 18])

In [107]:
mask=y>15
mask, y[mask]

(array([False, False, False,  True,  True]), array([16, 18]))

In [108]:
y[mask]=100
print(y)

[ 10  12  14 100 100]


### Problem 4

In [220]:
a=np.array([-3,-2,-1,0,1,2,3])

In [221]:
#as a function
def non_zero(a0):
    b=np.copy(a0)
    mask = b<0
    b[mask]=0
    return b

print(non_zero(a))

[0 0 0 0 1 2 3]


## Array Manipulation

## Shaping

In [114]:
A = np.arange(12)
print(A)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [117]:
A.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [118]:
A.reshape((2,-1))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [120]:
A=np.arange(12).reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
np.ravel(A)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
A.T, np.transpose(A)

(array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]), array([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]]))

In [125]:
A = np.arange(10).reshape((2,5))
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
x = A[:,1]
x

array([1, 6])

In [129]:
x.shape, x.ndim

((2,), 1)

In [131]:
x=np.arange(3)
x

array([0, 1, 2])

In [132]:
x.reshape((-1,1))

array([[0],
       [1],
       [2]])

## Stacking

In [140]:
A = np.arange(6).reshape((2,3))
B = np.zeros((4,3))
A

array([[0, 1, 2],
       [3, 4, 5]])

In [141]:
B

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [142]:
np.vstack((A,B,A))

array([[0., 1., 2.],
       [3., 4., 5.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 1., 2.],
       [3., 4., 5.]])

In [143]:
A=A.T
B=np.ones((3,4))

In [144]:
np.hstack((A,B,A))

array([[0., 3., 1., 1., 1., 1., 0., 3.],
       [1., 4., 1., 1., 1., 1., 1., 4.],
       [2., 5., 1., 1., 1., 1., 2., 5.]])

In [145]:
np.column_stack((A, np.zeros(3), np.ones(3), np.full(3,2)))

array([[0., 3., 0., 1., 2.],
       [1., 4., 0., 1., 2.],
       [2., 5., 0., 1., 2.]])

### Problem 5

In [146]:
A=np.array([[0,2,4],[1,3,5]])
B=np.array([[3,0,0],[3,3,0],[3,3,3]])
C=np.diag([-2,-2,-2])

In [166]:
One = np.column_stack((np.zeros((3,4)), A.T, np.eye(3)))
Two = np.column_stack((A, np.zeros_like(A), np.zeros_like(A)))
Three= np.column_stack((B, np.zeros_like(B), C))

In [167]:
One

array([[0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 2., 3., 0., 1., 0.],
       [0., 0., 0., 0., 4., 5., 0., 0., 1.]])

In [162]:
Two

array([[0, 2, 4, 0, 0, 0, 0, 0, 0],
       [1, 3, 5, 0, 0, 0, 0, 0, 0]])

In [163]:
Three

array([[ 3,  0,  0,  0,  0,  0, -2,  0,  0],
       [ 3,  3,  0,  0,  0,  0,  0, -2,  0],
       [ 3,  3,  3,  0,  0,  0,  0,  0, -2]])

In [168]:
np.vstack((One,Two,Three))

array([[ 0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0.,  0., -2.]])

## Array Broadcasting

In [170]:
A = np.arange(12).reshape((4,3))
x = np.arange(3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [171]:
x

array([0, 1, 2])

In [172]:
A+x

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13]])

In [174]:
y = np.arange(0, 40, 10).reshape((4,1))
A + y

array([[ 0,  1,  2],
       [13, 14, 15],
       [26, 27, 28],
       [39, 40, 41]])

In [175]:
x+y

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

## Numerical Computing with NumPy

## Universal Functions

In [178]:
x = np.arange(-2,3)
print(x, np.abs(x))

[-2 -1  0  1  2] [2 1 0 1 2]


In [179]:
np.sin(x)

array([-0.90929743, -0.84147098,  0.        ,  0.84147098,  0.90929743])

In [180]:
import math
print(math.exp(3), np.exp(3))

20.085536923187668 20.085536923187668


In [181]:
x = np.arange(-2, 3)
np.tan(x)

array([ 2.18503986, -1.55740772,  0.        ,  1.55740772, -2.18503986])

In [182]:
math.tan(x)

TypeError: only size-1 arrays can be converted to Python scalars

## Other Array Methods

In [183]:
A = np.arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [184]:
A.max()

8

In [187]:
#min by column
A.min(axis=0)

array([0, 1, 2])

In [188]:
# sum by row
A.sum(axis=1)

array([ 3, 12, 21])

### Problem 6

In [231]:
def myfun(A0):
    sums = A0.sum(axis=1)
    B = A0 / sums.reshape((len(sums),1))
    return B    

In [232]:
A = np.arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [233]:
print(myfun(A))

[[0.         0.33333333 0.66666667]
 [0.25       0.33333333 0.41666667]
 [0.28571429 0.33333333 0.38095238]]


### Problem 7

In [197]:
import os
os.chdir('C:/Users/schue/Documents/OSELab 2019/BootCamp2019/Computation/Wk1_PyIntro')
grid = np.load("grid.npy")

In [214]:
np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])

48477312

In [215]:
np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])

51267216

In [ ]:
#diagonal

In [216]:
np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])

40304286